# Generated by Django 4.0.4 on 2022-05-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firt_name',
            new_name='given_name',
        ),
    ]
